### ISSUE TITLE
TSQLT install

### ISSUE THREAD

**Issue by lastlink** [rr-wfm/MSBuild.Sdk.SqlProj#49] opened 2020-09-02 13:16 UTC
* how would we include tsqlt as part of this build?
* I'm trying to get tsqlt unit test framework to work w/ a dotnet core build on a linux machine for devops pipelines such as github actions

## troubleshooting
* if I could do a dacpac of tsql then I could include that for the models but that doesn't appear to be supported. such as from https://github.com/GoEddie/AdventureworksCI/tree/v0.2/src/Test/References
* I've been experimenting w/ https://github.com/lastlink/SQLCover/tree/f/tsql and trying to get tsql to work
```xml
<ItemGroup>
    <PreDeploy Include="..\..\..\..\tSQLt_V1.0.5873.27393\SetClrEnabled-linux.sql" />
  </ItemGroup>
  <ItemGroup>
    <!-- <Content Include="..\..\..\..\tSQLt_V1.0.5873.27393\tSQLt.class.sql" /> -->
  </itemGroup>
```
  * when I just include it, the file itself raw doesn't work. I suppose I could initialize a database and then export a new version fo the scripts.

**Comment by jmezach** [comment] 2020-09-03 06:11
I've had a look at [tSQLt](https://tsqlt.org/) since I have to admit I've never heard of it before. Looking through the docs it seems to rely on SQLCLR. When we started this project we made a deliberate choice to ignore SQLCLR initially since we weren't using it ourselves. That doesn't mean it can't be made to work, we just don't know what would be needed to make it work since we have no experience with it. If someone with a lot more experience with SQLCLR would be willing to help out here that would be awesome.

That being said, perhaps it would work if you wrap up the [tSQLt.dacpac](https://github.com/GoEddie/AdventureworksCI/blob/v0.2/src/Test/References/tSQLt.dacpac) into a NuGet package (possibly using the [NuGet Package Explorer](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer)) and make sure the `.dacpac` is inside the `tools` folder of the package you might be able to add that NuGet package as a `PackageReference` to your MSBuild.Sdk.SqlProj `.csproj`. That would essentially add the objects from `tSQLt.dacpac` to your model.

For the scripts [from here](https://github.com/lastlink/SQLCover/tree/f/tsql/tSQLt_V1.0.5873.27393) I am wondering what error you're seeing when you try to include them in your project. Adding them as a `PreDeploy` script should work, but you might hit #23 if you have multiple separate pre-deployment scripts you want to run. You could try putting them all into a single file to see if that helps. Including them as `Content` is probably not going to work because they are probably not DDL scripts.

**Comment by lastlink** [comment] 2020-10-28 13:24
It would be great if we could reference this dacpac directly rather than having to use a nuget package. Also see #82. I'm trying to get each view/ table to work and this sdk is missing build in sql server tables such as those on the **sys** schema.

**Comment by ErikEJ** [comment] 2024-04-03 08:05
@lastlink It looks like you got tSQLt to work: https://github.com/GoEddie/SQLCover/pull/60 - can we close this now?

**Comment by lastlink** [comment] 2024-07-15 18:57
I built the tsqlt on a windows container (not using this Linux compatible build tool). Exported the deploy sql and then ran that to get tsql working on Linux agent. Would be still nice to use on this tool

**Comment by ErikEJ** [comment] 2024-07-15 19:17
@goeddie @ lastlink So this is a duplicate of #109 perhaps??

**Comment by ErikEJ** [comment] 2024-07-31 16:15
Someone cracked it: https://www.nuget.org/packages/dotnet-sqltest

**Closed by ErikEJ** 2024-07-31 16:15 UTC
Labels: enhancement, help wanted, question
