### ISSUE TITLE
Remove documented limitation on SQLCMD merging

### ISSUE THREAD

**Issue by malevich-maxim** [rr-wfm/MSBuild.Sdk.SqlProj#80] opened 2020-10-13 09:36 UTC
LIMITATION: Currently there is no support for including other scripts from the pre- or post deployment script using the :r OtherScript.sql syntax. See this issue for more details.

didn't noticed any actual issues about that, I've tried to create my own project and it's failed coz of that problem. 
Is it working now or not? 
Also attached my project, maybe I did something wrong
[DatabaseTest.zip](https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/files/5370402/DatabaseTest.zip)

**Comment by jmezach** [comment] 2020-10-13 09:39
@malevich-maxim This should be fixed as of version 1.8.1 and you are using 1.9.0 in your test project so I am curious to know what doesn't work for you. Could you share the error you are receiving?

**Comment by malevich-maxim** [comment] 2020-10-13 14:23
@jmezach, sure, maybe stack trace will help

1>------ Build started: Project: DatabaseTest, Configuration: Debug Any CPU ------
1>Using package name DatabaseTest and version 1.0.0
1>Using SQL Server version Sql150
1>Adding C:\Work\ConsoleApp1\DatabaseTest\obj\Debug\predeploy.sql to the model
1>Adding C:\Work\ConsoleApp1\DatabaseTest\PreDeployment\Script.PreDeployment.sql to the model
1>Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
1> ---> Microsoft.SqlServer.Dac.Model.DacModelException: Add or update objects failed due to the following errors:
1>EXEC : warning SQL70501: DML statements cannot be modeled.
1>EXEC : error SQL46010: Incorrect syntax near \.
1>
1>   at Microsoft.SqlServer.Dac.Model.SqlSchemaModelObjectService.ThrowIfModelErrorsExist(String errorMessage)
1>   at Microsoft.SqlServer.Dac.Model.SqlSchemaModelObjectService.DoAddOrUpdateObjects(String inputScript, String sourceName, TSqlObjectOptions options)
1>   at Microsoft.SqlServer.Dac.Model.SqlSchemaModelObjectService.AddOrUpdateObjects(String inputScript, String sourceName, TSqlObjectOptions options)
1>   at Microsoft.SqlServer.Dac.Model.TSqlModel.AddOrUpdateObjects(String inputScript, String sourceName, TSqlObjectOptions options)
1>   at MSBuild.Sdk.SqlProj.DacpacTool.PackageBuilder.AddInputFile(FileInfo inputFile) in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/src/DacpacTool/PackageBuilder.cs:line 79
1>   at MSBuild.Sdk.SqlProj.DacpacTool.Program.BuildDacpac(BuildOptions options) in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/src/DacpacTool/Program.cs:line 117
1>   --- End of inner exception stack trace ---
1>   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
1>   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
1>   at System.Delegate.DynamicInvokeImpl(Object[] args)
1>   at System.Delegate.DynamicInvoke(Object[] args)
1>   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
1>   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
1>--- End of stack trace from previous location where exception was thrown ---
1>   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__21_0>d.MoveNext()
1>--- End of stack trace from previous location where exception was thrown ---
1>   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
1>--- End of stack trace from previous location where exception was thrown ---
1>   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseVersionOption>b__0>d.MoveNext()
1>--- End of stack trace from previous location where exception was thrown ---
1>   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseTypoCorrections>b__0>d.MoveNext()
1>--- End of stack trace from previous location where exception was thrown ---
1>   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__22_0>d.MoveNext()
1>--- End of stack trace from previous location where exception was thrown ---
1>   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__20_0>d.MoveNext()
1>--- End of stack trace from previous location where exception was thrown ---
1>   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__11_0>d.MoveNext()
1>--- End of stack trace from previous location where exception was thrown ---
1>   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
1>--- End of stack trace from previous location where exception was thrown ---
1>   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
1>C:\Users\User\.nuget\packages\msbuild.sdk.sqlproj\1.9.0\Sdk\Sdk.targets(196,5): error MSB3073: The command "dotnet "C:\Users\User\.nuget\packages\msbuild.sdk.sqlproj\1.9.0\Sdk\../tools/netcoreapp3.1/DacpacTool.dll" build -o "obj\Debug\netstandard2.0\DatabaseTest.dacpac" -n "DatabaseTest" -v "1.0.0" -sv Sql150 -i "obj\Debug\netstandard2.0\DatabaseTest.InputFiles.txt"    --predeploy PreDeployment\Script.PreDeployment.sql   " exited with code 1.
1>Done building project "DatabaseTest.csproj" -- FAILED.

**Comment by ErikEJ** [comment] 2020-10-13 15:21
Or rename the folder from PreDeployment to Pre-Deployment :-)

**Comment by jeffrosenberg** [comment] 2020-10-13 15:41
> Or rename the folder from PreDeployment to Pre-Deployment :-)

Good point, although I think removing `obj` will still be needed in my experience. We might want to exclude that from the model automatically, since nobody would ever want it.

**Comment by jmezach** [comment] 2020-10-13 16:33
@jeffrosenberg If the merged SQLCMD scripts are written to `obj` then yes we should probably add that folder as a `<Compile Remove="obj/**/*.sql" />` [here](https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/blob/0fb4ae0e6f5380fbadc8ef4a52ff0b9b3737d276/src/MSBuild.Sdk.SqlProj/Sdk/Sdk.props#L44).

**Comment by malevich-maxim** [comment] 2020-10-14 09:11
Thanks for all of you for help, and so sorry for inattentiveness

**Comment by jmezach** [comment] 2020-10-14 12:02
@malevich-maxim No problem. Thanks for reporting this. It still triggered us that we need to remove the documented limitation.

**Comment by jeffrosenberg** [comment] 2020-10-16 12:14
> @jeffrosenberg If the merged SQLCMD scripts are written to `obj` then yes we should probably add that folder as a `<Compile Remove="obj/**/*.sql" />` [here](https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/blob/0fb4ae0e6f5380fbadc8ef4a52ff0b9b3737d276/src/MSBuild.Sdk.SqlProj/Sdk/Sdk.props#L44)

@jmezach sorry for my slow response, it's been a crazy week at work! I agree, I'll log an issue for that and take care of it today or early next week.

**Comment by jeffrosenberg** [comment] 2020-10-20 01:43
@jmezach not sure what's changed, but I wasn't able to reproduce the issue regarding the `obj/` directory. I know I've seen this before, and I see it in the stack trace [in this comment above](https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/issues/80#issuecomment-707774125), but when I actually tried reproducing, I never saw a `.sql` file appear in that directory. So I'm not going to push a change to that, but I will be pushing a small PR to update the documentation for this issue.

**Closed** 2020-10-20 08:00 UTC
Labels: documentation
