### ISSUE TITLE
Support for SqlXmlSchemaCollection

### ISSUE THREAD

**Issue by greektreat** [rr-wfm/MSBuild.Sdk.SqlProj#242] opened 2021-12-24 15:13 UTC
I am unable to build the dacpac because It doesn't understand what to do with Types -> XML Schema Collections It also is using Service broker but i belive the issue is with  XML Schema Collections . Is there any work around or solution to solve the issue?

**Comment by jmezach** [comment] 2021-12-27 08:25
@greektreat Could you share the contents of your project file and any errors you're getting? That would help us to figure out what the issue is.

**Comment by greektreat** [comment] 2022-01-18 15:09
@jmezach thanks for the reply here is the detailed error meessages and attached is the csproj as txt

```

Error	MSB3073	The command "dotnet "C:\Users\mkimonos\.nuget\packages\msbuild.sdk.sqlproj\2.0.0-beta.1\Sdk\../tools/net6.0/DacpacTool.dll" build -o "build/obj\Debug\TCC.Broker.dacpac" -n "TCCBroker.Sql.Build" -v "1.0.0" -sv Sql150 -i "build/obj\Debug\TCCBroker.Sql.Build.InputFiles.txt"   -p Trustworthy=True -p ServiceBrokerOption=EnableBroker         -tdn "TCC.Broker"" exited with code 1.	TCCBroker.Sql.Build	C:\Users\mkimonos\.nuget\packages\msbuild.sdk.sqlproj\2.0.0-beta.1\Sdk\Sdk.targets	229	


Error	SQL71501	SqlMessageType: [msTransaction] has an unresolved reference to SqlXmlSchemaCollection [tcc].[Transaction].	TCCBroker.Sql.Build	C:\TFGIT\TransactionBroker.Sql\src\Service Broker\Message Types\msTransaction.sql	2	

Error	SQL71501	SqlMessageType: [msTransactionAcknowledgment] has an unresolved reference to SqlXmlSchemaCollection [tcc].[TransactionAcknowledgment].	TCCBroker.Sql.Build	C:\TFGIT\TransactionBroker.Sql\src\Service Broker\Message Types\msTransactionAcknowledgment.sql	2	
```

[TCCBroker.Sql.Build.TXT](https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/files/7890070/TCCBroker.Sql.Build.TXT)

**Comment by jmezach** [comment] 2022-01-18 15:42
@greektreat How are you defining those SqlXmlSchemaCollection objects in your SQL scripts? Based on the project file it seems that the XML schema files aren't included in the build, but I guess you'll have to define them in your project somehow. I don't have much experience with XML schemas in SQL.

**Comment by greektreat** [comment] 2022-02-15 19:06
> @greektreat To be honest I have no idea what's going wrong here. Do you have an existing `.sqlproj` file that you're willing to share where this is working? Perhaps that would give us a clue as to how this is supposed to work.

privately yes

**Comment by jmezach** [comment] 2022-02-16 08:13
Would it be possible to share just the relevant details? I'm particularly interested to see how the `.xsd` is referenced from the project file in the `.sqlproj` case.

**Comment by ErikEJ** [comment] 2022-11-22 14:35
Closing as the requested additional information was never supplied.

**Closed by ErikEJ** 2022-11-22 14:35 UTC
