### ISSUE TITLE
missing references to build in table sys

### ISSUE THREAD

**Issue by lastlink** [rr-wfm/MSBuild.Sdk.SqlProj#82] opened 2020-10-28 13:04 UTC
while trying to implement tsqlt sql classes I'm getting missing references to the **sys** schema. e.g. **[sys].[extended_properties]**.

```bat
ModelValidationError 
error SQL71501: SqlView: [tSQLt].[TestClasses] contains an unresolved reference to an object. Either the object does not exist or the reference is ambiguous because it could refer to any of the following objects: [sys].[extended_properties].[ep]::[name], [sys].[extended_properties].[name] or [sys].[schemas].[ep]::[name].
```

**Comment by jmezach** [comment] 2020-10-28 13:38
This is probably related to #64. We've asked Microsoft if we are allowed to redistribute the `master.dacpac`'s of various versions of SQL Server, but so far we haven't heard anything yet.

**Comment by jmezach** [comment] 2020-12-14 15:15
Closing this as a duplicate of #64

**Closed by jmezach** 2020-12-14 15:15 UTC
Labels: question
