### ISSUE TITLE
Correct support for post-/pre-deployment templates

### ISSUE THREAD

**Issue by denis-peshkov** [rr-wfm/MSBuild.Sdk.SqlProj#121] opened 2021-02-12 07:33 UTC
I have Script.PreDeployment.sql
```sql
/*
 Pre-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be executed before the build script.	
 Use SQLCMD syntax to include a file in the pre-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the pre-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/

PRINT 'Begin executing Script.PreDeployment.sql'
GO

PRINT 'Start populating Reference Lookup Data'

:r .\Pre-Deployment\20210120_01_initial.sql

PRINT 'End populating Reference Lookup Data'
```
but building the project cause an error
```
Build started...
1>------ Build started: Project: Database2, Configuration: Debug Any CPU ------
1>Using package name Database2 and version 1.0.0
1>Using SQL Server version Sql150
1>Adding P:\Work\NewGround\340Basics\src\Database2\Scripts\Script.PreDeployment.sql to the model
1>Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
1> ---> Microsoft.SqlServer.Dac.Model.DacModelException: Add or update objects failed due to the following errors:
1>EXEC : error SQL46010: Incorrect syntax near \.
1>
1>   at Microsoft.SqlServer.Dac.Model.SqlSchemaModelObjectService.ThrowIfModelErrorsExist(String errorMessage)
1>   at Microsoft.SqlServer.Dac.Model.SqlSchemaModelObjectService.DoAddOrUpdateObjects(String inputScript, String sourceName, TSqlObjectOptions options)
1>   at Microsoft.SqlServer.Dac.Model.SqlSchemaModelObjectService.AddOrUpdateObjects(String inputScript, String sourceName, TSqlObjectOptions options)
1>   at Microsoft.SqlServer.Dac.Model.TSqlModel.AddOrUpdateObjects(String inputScript, String sourceName, TSqlObjectOptions options)
1>   at MSBuild.Sdk.SqlProj.DacpacTool.PackageBuilder.AddInputFile(FileInfo inputFile) in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/src/DacpacTool/PackageBuilder.cs:line 85
1>   at MSBuild.Sdk.SqlProj.DacpacTool.Program.BuildDacpac(BuildOptions options) in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/src/DacpacTool/Program.cs:line 122
1>   --- End of inner exception stack trace ---
1>   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
1>   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
1>   at System.Delegate.DynamicInvokeImpl(Object[] args)
1>   at System.Delegate.DynamicInvoke(Object[] args)
1>   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
1>   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
1>--- End of stack trace from previous location ---
1>   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__21_0>d.MoveNext()
1>--- End of stack trace from previous location ---
1>   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
1>--- End of stack trace from previous location ---
1>   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseVersionOption>b__0>d.MoveNext()
1>--- End of stack trace from previous location ---
1>   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseTypoCorrections>b__0>d.MoveNext()
1>--- End of stack trace from previous location ---
1>   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__22_0>d.MoveNext()
1>--- End of stack trace from previous location ---
1>   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__20_0>d.MoveNext()
1>--- End of stack trace from previous location ---
1>   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__11_0>d.MoveNext()
1>--- End of stack trace from previous location ---
1>   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
1>--- End of stack trace from previous location ---
1>   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
1>C:\Users\denis\.nuget\packages\msbuild.sdk.sqlproj\1.11.3\Sdk\Sdk.targets(196,5): error MSB3073: The command "dotnet "C:\Users\denis\.nuget\packages\msbuild.sdk.sqlproj\1.11.3\Sdk\../tools/netcoreapp5.0/DacpacTool.dll" build -o "obj\Debug\netstandard2.0\Database2.dacpac" -n "Database2" -v "1.0.0" -sv Sql150 -i "obj\Debug\netstandard2.0\Database2.InputFiles.txt"       " exited with code 1.
1>Done building project "Database2.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```
with next error
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		SQL80001: Incorrect syntax near ':'.	Database2	P:\Work\NewGround\340Basics\src\Database2\Scripts\Script.PreDeployment.sql	19	
Error	SQL46010	Incorrect syntax near \.	Database2	P:\Work\NewGround\340Basics\src\Database2\EXEC	1	
Error	MSB3073	The command "dotnet "C:\Users\denis\.nuget\packages\msbuild.sdk.sqlproj\1.11.3\Sdk\../tools/netcoreapp5.0/DacpacTool.dll" build -o "obj\Debug\netstandard2.0\Database2.dacpac" -n "Database2" -v "1.0.0" -sv Sql150 -i "obj\Debug\netstandard2.0\Database2.InputFiles.txt"       " exited with code 1.	Database2	C:\Users\denis\.nuget\packages\msbuild.sdk.sqlproj\1.11.3\Sdk\Sdk.targets	196	
```

**Comment by ErikEJ** [comment] 2021-02-12 07:38
Is it in the correct folder?

**Comment by jmezach** [comment] 2021-02-12 07:39
This is kind of by design since we include every `.sql` file by default and assume that they are DDL scripts that built up the model. You can fix this by changing the build action to `PreDeploy` in your project file.

@ErikEJ @jeffrosenberg Perhaps we should use this as an opportunity to improve the error message here. This is fairly common question we get.

**Comment by ErikEJ** [comment] 2021-02-12 07:43
How would we know if a particular file is a pre / post file?

**Comment by jmezach** [comment] 2021-02-12 07:49
;) I'm hoping the `DacModelException` would tell us in this case. But I haven't yet proved that theory.

**Comment by jeffrosenberg** [comment] 2021-02-12 12:07
> How would we know if a particular file is a pre / post file?

One thing we could do is simply look for files named PreDeployment.sql or PostDeployment.sql when this error is raised. It's rare that people choose a different name, in my experience.

**Comment by ErikEJ** [comment] 2021-02-12 13:15
Yes, a filename ending with that could indicate it, but there is no way to be sure.

**Comment by jeffrosenberg** [comment] 2021-02-12 13:40
Understood, but I think it gets us 95% or more of the cases for very little effort. If we find a more reliable way, I'm all for it, but if not, I'd take something imperfect over nothing at all.

**Comment by iSeiryu** [comment] 2021-04-20 18:13
Ran into the same issue.
```sql
:r "MyTable.sql"
```
gives me
```
Adding path\to\Script.PostDeployment.sql to the model
  Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   ---> Microsoft.SqlServer.Dac.Model.DacModelException: Add or update objects failed due to the following errors:
error SQL46010: Incorrect syntax near :. 
```

Removing it builds just fine.

> How would we know if a particular file is a pre / post file?

Maybe add some kind of `Exclude` property to `.csproj`?

**Comment by jmezach** [comment] 2022-02-16 08:28
MSBuild.Sdk.SqlProj includes all `.sql` files by default. We do explicitly exclude certain folders (see [here](https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/blob/df0ca45534c00a624b3a175be976e729fc9b9cac/src/MSBuild.Sdk.SqlProj/Sdk/Sdk.props#L40)), such as `Pre-Deployment` and `Post-Deployment`. However, there doesn't seem to be a common name for these folders, as we've seen a couple of issues (for example #137 and #260) surrounding this topic. Unfortunately that makes it pretty hard to have sensible defaults. We do have some documentation on this in the [README](https://github.com/rr-wfm/MSBuild.Sdk.SqlProj#workaround-for-parser-errors-sql46010) so I don't think there's much more we can do here so I'll close this issue. If you feel there's more we can do, feel free to re-open.

**Closed by jmezach** 2022-02-16 08:28 UTC
Labels: question
