### ISSUE TITLE
:r relative path not working on linux

### ISSUE THREAD

**Issue by PyroSA** [rr-wfm/MSBuild.Sdk.SqlProj#114] opened 2021-01-21 22:29 UTC
Version: MSBuild.Sdk.SqlProj/1.11.1

We're using mcr.microsoft.com/dotnet/core/sdk:3.1-buster on our docker-based build.

**Expectation:** 
:r scripts in a relative path should be included and and run in the post-deploy script.

**Actual:**
Error - file not found.

**Detail:**
The container is Debian 10 based - Linux.

When running dotnet build on there for the dacpac project, we have an issue with paths.

We have our data insertions separated into scripts files under a data folder.
These are then included in the post-build script as:
```sql
:r .\Data\InsertScript1.sql
:r .\Data\InsertScript2.sql
```

But when we run the build from a Dockerfile, we get the following output:
```
Microsoft (R) Build Engine version 16.7.2+b60ddb6f4 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /src/DB.build.csproj (in 222 ms).
  Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   ---> System.IO.FileNotFoundException: Could not find file '/src/.\Data\InsertScript1.sql'.
  File name: '/src/.\Data\InsertScript1.sql'
     at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
     at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
     at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
     at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
     at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
     at System.IO.StreamReader..ctor(String path)
     at MSBuild.Sdk.SqlProj.DacpacTool.ScriptParser.Microsoft.SqlTools.ServiceLayer.BatchParser.ICommandHandler.Include(TextBlock includeBlock, TextReader& stream, String& newFilename) in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/src/DacpacTool/ScriptParser.cs:line 64
     at Microsoft.SqlTools.ServiceLayer.BatchParser.Parser.ParseInclude() in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/sqltoolsservice/src/Microsoft.SqlTools.ManagedBatchParser/BatchParser/Parser.cs:line 302
     at Microsoft.SqlTools.ServiceLayer.BatchParser.Parser.ParseLines() in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/sqltoolsservice/src/Microsoft.SqlTools.ManagedBatchParser/BatchParser/Parser.cs:line 394
     at Microsoft.SqlTools.ServiceLayer.BatchParser.Parser.Parse() in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/sqltoolsservice/src/Microsoft.SqlTools.ManagedBatchParser/BatchParser/Parser.cs:line 233
     at MSBuild.Sdk.SqlProj.DacpacTool.ScriptParser.Parse() in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/src/DacpacTool/ScriptParser.cs:line 28
     at MSBuild.Sdk.SqlProj.DacpacTool.ScriptParser.CollectFileNames() in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/src/DacpacTool/ScriptParser.cs:line 35
     at MSBuild.Sdk.SqlProj.DacpacTool.ScriptInspector.AddIncludedFiles(FileInfo file) in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/src/DacpacTool/ScriptInspector.cs:line 28
     at MSBuild.Sdk.SqlProj.DacpacTool.Program.InspectIncludes(InspectOptions options) in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/src/DacpacTool/Program.cs:line 149
     --- End of inner exception stack trace ---
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
     at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
     at System.Delegate.DynamicInvokeImpl(Object[] args)
     at System.Delegate.DynamicInvoke(Object[] args)
     at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
     at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__21_0>d.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseVersionOption>b__0>d.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseTypoCorrections>b__0>d.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__22_0>d.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__20_0>d.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__11_0>d.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
/root/.nuget/packages/msbuild.sdk.sqlproj/1.11.1/Sdk/Sdk.targets(151,5): error MSB3073: The command "dotnet "/root/.nuget/packages/msbuild.sdk.sqlproj/1.11.1/Sdk/../tools/netcoreapp3.1/DacpacTool.dll" collect-includes --predeploy Script.PreDeployment.sql --postdeploy Script.PostDeployment.sql " exited with code 1. [/src/DB.build.csproj]
```

Changing the paths to ./ in the SQL file gives an "Incorrect syntax near :" error.

As a workaround we've moved our scripts to be in the same folder as the post build script.

**Comment by jmezach** [comment] 2021-01-22 07:13
This sounds like a bug. I'm guessing we'll need to normalize the included path so that it is compatible with the underlying file system which obviously is different between operating systems.

@jeffrosenberg If I remember correctly you worked on this feature. Do you know if there's a place in the pipeline where we could fix this?

**Comment by jeffrosenberg** [comment] 2021-01-22 12:27
@jmezach I have a crazy day today, but happy to look at it over the weekend

**Comment by jmezach** [comment] 2021-01-22 12:56
@jeffrosenberg Sure, no rush. From what I understand @PyroSA already has a workaround for now.

**Comment by PyroSA** [comment] 2021-01-22 17:32
Correct, Workaround is to put the postdeploy.sql and the childscript.sql in the same folder, so you don't need a path.

This should get the same error:
https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/blob/master/test/TestProjectWithPrePost/Pre-Deployment/Script.PreDeployment.RelativePathIncludes.sql

**Comment by jeffrosenberg** [comment] 2021-01-25 01:16
@jmezach I would say the solution to normalizing paths between operating systems is to just use a forward-slash, as forward-slash is compatible with all operating systems, including Windows. Since there's an existing way to handle normalizing paths, I'd say that would be more robust than trying to convert them within our project.

In fact, I can confirm this works fine on my own company's projects -- when we switched to using this SDK, we converted all backslashes to forward-slashes, and they work cross-platform.

What I'm confused by is this comment by @PyroSA:

> Changing the paths to ./ in the SQL file gives an "Incorrect syntax near :" error.

I'm pretty sure this works in the test you linked, and I know that my company uses this syntax as well. Would you be able to provide a more complete example of what the script looks like using forward-slashes? In the meantime, I'll make this particular test a bit more robust in case there's some behavior here it's not capturing.

**Comment by PyroSA** [comment] 2021-01-25 16:14
@jeffrosenberg 

Weirdly - this seems to work as expected now that the post-deply script in a post sub-folder.

With the same-folder setup:
:r ./InsertScripts.sql -> works
:r InsertScripts.sql -> works
:r .\InsertSrcipt.sql -> fails (file not found)

Moving the script into a post/Data subfolder:
With the same-folder setup:
:r ./Data/InsertScripts.sql -> works
:r Data/InsertScripts.sql -> works
:r .\Data\InsertSrcipt.sql -> fails (file not found)

There might be some other weird interaction with files here.
My csproj had:
```
  <ItemGroup>
    <Content Include="dbo\**\*.sql" />
    <Content Remove="post\*.sql" />
    <Content Remove="pre\*.sql" />
  </ItemGroup>
  <ItemGroup>
    <PreDeploy Include="pre\.PreDeployment.sql" />
    <PostDeploy Include="post\.PostDeployment.sql" />
  </ItemGroup>
```

With pre and post removed, we still see this in the log:
```
  Adding /src/post/Data/InsertScript1.sql to the model
  Adding /src/post/Data/InsertScript2.sql to the model
  Adding /src/dbo/Stored Procedures/Foo.sql to the model
  Adding /src/dbo/Tables/Bar.sql to the model
```
I'm not sure why the /src/post/Data scripts are included.

**Comment by jeffrosenberg** [comment] 2021-01-25 16:18
If this is running on linux, I think you'll need to use all forward-slashes for paths. I think that's where the remaining issues are coming from. They're portable to Windows, so it should be safe to just do a global replace.

**Comment by PyroSA** [comment] 2021-01-25 16:22
Initially the forward slashes were not working, but it might be an edge case somewhere.
With the current folder structure it works as expected.

The files being included that were not part of the csproj might be part of this.
I saw files added from /src/obj/ before I deleted that folder, even though it was not referenced in the csproj.

**Comment by jeffrosenberg** [comment] 2021-01-25 16:40
We've seen that issue before, and I feel like we talked about excluding `obj` from the content that gets built, but looking at the code, apparently we didn't do it. @jmezach @ErikEJ this seems like as good a time as any to add that exclusion, would you agree? I can push a quick PR for that.

**Comment by PyroSA** [comment] 2021-01-25 16:46
The 'add post/InsertScript.sql to model' no longer seems to appear.
I fiddled some, but made no real changes that would remove them.
Some of the unexpected behaviour might be caused by docker's cache - locally I now build those with no-cache to remove that unknown.

I'll be spending some time seeing if the actual dacpac works and extend it to include more tables/sprocs, but will keep an eye on this.

**Comment by jmezach** [comment] 2021-01-25 16:59
@jeffrosenberg Yeah, I was also under the impression that we didn't include anything in the bin/obj folders either but I would have expected that [here](https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/blob/b5053dac8260f21f0c124c6a3b1fa1753dad3226/src/MSBuild.Sdk.SqlProj/Sdk/Sdk.props#L39-L45) and I don't see it. Might be good to add that.

**Comment by jeffrosenberg** [comment] 2021-01-25 17:10
Yeah, agreed. I'll send that PR this evening my time.

**Comment by jeffrosenberg** [comment] 2021-01-26 00:59
@PyroSA just had another look at your comment above regarding the /src/post/Data scripts being included. While I stand by my general comment about using forward-slashes, I think you also need to use the globstar pattern here to cover subdirectories recursively:

```xml
  <ItemGroup>
    <Content Include="dbo/**/*.sql" />
    <Content Remove="post/**/*.sql" />
    <Content Remove="pre/**/*.sql" />
  </ItemGroup>
```

**Comment by PyroSA** [comment] 2021-01-26 03:23
> @PyroSA just had another look at your comment above regarding the /src/post/Data scripts being included. While I stand by my general comment about using forward-slashes, I think you also need to use the globstar pattern here to cover subdirectories recursively:
> 
> ```
>   <ItemGroup>
>     <Content Include="dbo/**/*.sql" />
>     <Content Remove="post/**/*.sql" />
>     <Content Remove="pre/**/*.sql" />
>   </ItemGroup>
> ```
Correct - Only noticed that with the post/data/InsertScript.sql later.
Might have been why I saw the post scripts in the added list, with the caching causing a post/data script to remain after it was removed in the actual source folder.
We're sticking with the flat structure for now,

**Comment by BjBlazkowicz** [comment] 2021-01-27 08:16
Hi,

I get syntax errors on Windows when trying to include a post deployment script. Is this related?

```
Microsoft.SqlServer.Dac.Model.DacModelException: Add or update objects failed due to the following errors:
EXEC : error SQL46010: Incorrect syntax near \.
```

**Comment by jmezach** [comment] 2021-01-27 10:27
@BjBlazkowicz The error message suggests that the script file is part of the build in which SQLCMD syntax is not supported. You'll probably want to change the build action for the offending script to `None` and make sure it is included in your pre or post deployment script using the `:r <script.sql>` syntax.

**Comment by BjBlazkowicz** [comment] 2021-01-28 10:25
@jmezach Thanks for your input.

It seems that it only works if I do a 'Content Remove' on the post deploy scripts also:

```
<Project Sdk="MSBuild.Sdk.SqlProj/1.11.2">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <SqlServerVersion>SqlAzure</SqlServerVersion>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="PostDeploy\*.sql" />
    <None Include="PostDeploy\*.sql" />
  </ItemGroup>

  <ItemGroup>
    <PostDeploy Include=".\PostDeploy\PostDeployment.sql" />
  </ItemGroup>

</Project>
```

**Comment by jmezach** [comment] 2021-01-28 11:51
@BjBlazkowicz Yes, that's indeed what's required and what I believe is documented in the [README.md](https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/blob/master/README.md) as well but if you feel there's room for improvement there please let us know. Do note that by default we exclude the `Pre-Deployment` and `Post-Deployment` folders as noted in the README so you could rename `PostDeploy` to `Post-Deployment` so you don't have to make changes to your project file.

@PyroSA It is my current understanding that your issues is resolved so I'm going to go ahead and close this issue, but feel free to re-open if that is not the case.

**Closed by jmezach** 2021-01-28 11:51 UTC
Labels: bug
