### ISSUE TITLE
Let configure packing dacpac with required nuspec next to csproj

### ISSUE THREAD

**Issue by iremezoff** [rr-wfm/MSBuild.Sdk.SqlProj#377] opened 2022-12-16 08:50 UTC
I guess restriction as such as having nuspec file next to csproj is very strict.
Typical csproj (e.g., of web sdk) doesn't require this file and lets set up nuspec attributes inside, see official doc [here ](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-pack) and [here](https://learn.microsoft.com/en-us/nuget/reference/msbuild-targets#pack-target).

During building and packing nuspec is created implicitly in obj directory and used to make a package.

Is there a plan to introduce such standard way to build packages? Unfortunately to myself, I'm not well-familiar with msbuild tasks so I can't make a PR with enough level of quality.

**Comment by ErikEJ** [comment] 2024-03-16 16:30
Duplicate of #283

**Closed by ErikEJ** 2024-03-16 16:30 UTC
